// Generated by scripts/package-downloads.mjs. Do not edit.
// Measured byte sizes of each downloadable file, by model and kind.
export const DOWNLOAD_BYTES: Record<string, Record<string, number>> = {
  "starfighter": {
    "web_glb": 1282696,
    "source_blend": 5356028,
    "textures_zip": 4778394
  },
  "tie-fighter": {
    "web_glb": 848548,
    "source_blend": 4888270,
    "textures_zip": 4491612
  },
  "at-at": {
    "source_blend": 2454839
  }
}
