// Generated by scripts/make-posters.mjs. Do not edit.
export const PLATE_WIDTHS: Record<string, Record<string, number[]>> = {
  "starfighter": {
    "poster": [
      400,
      800,
      1600
    ],
    "top": [
      400,
      800,
      1600
    ],
    "front": [
      400,
      800,
      1600
    ],
    "profile": [
      400,
      800,
      1600
    ],
    "rear": [
      400,
      800,
      1600
    ],
    "detail-cockpit": [
      400,
      800
    ],
    "detail-exhaust": [
      400,
      800
    ],
    "detail-intake": [
      400,
      800
    ],
    "seam": [
      400,
      800
    ],
    "first": [
      400,
      800
    ]
  },
  "tie-fighter": {
    "poster": [
      400,
      800
    ],
    "front": [
      400,
      800
    ],
    "side": [
      400,
      800
    ],
    "top": [
      400,
      800
    ],
    "rear": [
      400,
      800
    ],
    "detail-hub": [
      400,
      800
    ],
    "detail-window": [
      400,
      800
    ],
    "detail-panel": [
      400,
      800
    ],
    "seam": [
      400,
      800
    ]
  },
  "at-at": {
    "poster": [
      400,
      800,
      1600
    ],
    "front": [
      400,
      800,
      1600
    ],
    "side": [
      400,
      800,
      1600
    ],
    "top": [
      400,
      800
    ],
    "rear": [
      400,
      800
    ],
    "detail-knee": [
      400,
      800
    ],
    "detail-foot": [
      400,
      800
    ],
    "detail-guns": [
      400,
      800
    ],
    "first": [
      400,
      800
    ]
  }
}

export interface SeamSpec { view: [number, number, number]; stars: boolean; aspect: number; fill: number; backdrop: string }
export const SEAMS: Record<string, SeamSpec> = {
  "starfighter": {
    "view": [
      -2.15,
      0.42,
      0.28
    ],
    "stars": true,
    "aspect": 0.5625,
    "fill": 0.4583,
    "backdrop": "#091426"
  },
  "tie-fighter": {
    "view": [
      1,
      0.001,
      0
    ],
    "stars": false,
    "aspect": 0.9569,
    "fill": 0.375,
    "backdrop": "#bdbebf"
  }
}
