/**
 * Exported GLB -> web GLB.
 *
 * The Blender exports are 5-6 MB because they carry 2048px PNG bakes and
 * un-deduplicated geometry. The inspector needs them under ~1.5 MB.
 *
 * Geometry is deduplicated and welded, never compressed: the savings come from
 * the textures. A model can opt into meshoptimizer simplification and
 * KHR_mesh_quantization (MODELS[].web) when its geometry is the heavy part, as
 * the 106k-triangle battle droid's is. Textures are resized and re-encoded to WebP,
 * which every target browser decodes natively -- KTX2/Basis would be smaller on
 * the GPU but needs a transcoder bundle that costs more than it saves at this
 * texture count.
 *
 * Normal maps keep more quality than base colour: banding in a normal map reads
 * as visible faceting on the hull.
 */
import { mkdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { NodeIO } from '@gltf-transform/core'
import { ALL_EXTENSIONS } from '@gltf-transform/extensions'
import { dedup, prune, weld, simplify, resample, textureCompress, flatten, join as joinMeshes, quantize } from '@gltf-transform/functions'
import { MeshoptSimplifier, MeshoptEncoder } from 'meshoptimizer'
import sharp from 'sharp'
import { writeFileSync } from 'node:fs'
import { ROOT, sourceRoot, MODELS, bytes } from './_shared.mjs'
import { measureAnchors } from './anchors.mjs'

const MAX_TEXTURE = 1024
const only = process.argv[2]

await MeshoptSimplifier.ready
await MeshoptEncoder.ready

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS)
const measured = {}
const outDir = join(ROOT, 'public/assets/models')
mkdirSync(outDir, { recursive: true })

for (const model of MODELS) {
  if (only && model.slug !== only) continue
  if (!model.glb) {
    console.log(`- ${model.slug}: no GLB export yet (needs its bake pass), skipping`)
    continue
  }

  const src = join(sourceRoot(), model.project, model.glb)
  const before = statSync(src).size

  // Measure before any transform, from the geometry exactly as Blender exported it.
  const m = await measureAnchors(model.slug, src)
  if (m) {
    measured[model.slug] = m
    console.log(`  ${model.slug} size ${m.size.join(' x ')} (glTF x,y,z) anchors: ${Object.keys(m.anchors).join(', ')}; ${m.hull.length} silhouette points`)
  }
  const doc = await io.read(src)

  // Report what came in, so a regression in the Blender export is visible here.
  const triCount = doc.getRoot().listMeshes()
    .flatMap((m) => m.listPrimitives())
    .reduce((n, p) => n + (p.getIndices()?.getCount() ?? 0) / 3, 0)

  // Per-model web settings (MODELS[].web), opt-in. Models without them come out
  // exactly as before. A dense model can ask for simplification and quantised
  // vertex attributes (KHR_mesh_quantization, which three.js's GLTFLoader reads
  // natively -- no decoder to ship). The downloadable export keeps full detail.
  const web = model.web ?? {}
  await doc.transform(
    dedup(),
    flatten(),
    joinMeshes(),
    weld({ tolerance: 0.0001 }),
    resample(),
    simplify({ simplifier: MeshoptSimplifier, ratio: web.simplify ?? 1.0, error: web.simplify ? 0.002 : 0.0001 }),
    ...(web.quantize ? [quantize()] : []),
    // Normal maps tolerate far less compression than base colour.
    textureCompress({
      encoder: sharp,
      targetFormat: 'webp',
      resize: [MAX_TEXTURE, MAX_TEXTURE],
      quality: 90,
      slots: /normal/i,
    }),
    textureCompress({
      encoder: sharp,
      targetFormat: 'webp',
      resize: [MAX_TEXTURE, MAX_TEXTURE],
      quality: 76,
    }),
    prune({ keepAttributes: false, keepLeaves: false })
  )

  // A rigged model must come out still rigged: every mesh with skinning data
  // bound to a skin, and every clip kept. Otherwise it would load as a statue.
  const srcDoc = await io.read(src)
  const clipsIn = srcDoc.getRoot().listAnimations().length
  if (srcDoc.getRoot().listSkins().length) {
    const unbound = doc.getRoot().listNodes().filter((n) =>
      n.getMesh()?.listPrimitives().some((p) => p.getAttribute('JOINTS_0')) && !n.getSkin()
    )
    if (unbound.length) throw new Error(`${model.slug}: ${unbound.map((n) => n.getName()).join(', ')} lost its skin`)
    if (doc.getRoot().listAnimations().length !== clipsIn)
      throw new Error(`${model.slug}: ${clipsIn} clips in, ${doc.getRoot().listAnimations().length} out`)
  }

  const out = join(outDir, `${model.slug}.glb`)
  await io.write(out, doc)
  const after = statSync(out).size

  console.log(
    `${model.slug.padEnd(14)} ${bytes(before).padStart(9)} -> ${bytes(after).padStart(9)}` +
      `  (${(100 - (after / before) * 100).toFixed(0)}% smaller, ${Math.round(triCount).toLocaleString()} tris, ` +
      `${doc.getRoot().listMaterials().length} materials, ${doc.getRoot().listTextures().length} textures)`
  )
}

if (!only) {
  const out = join(ROOT, 'src/lib/anchors.generated.ts')
  writeFileSync(
    out,
    `// Generated by scripts/optimize-glb.mjs from the exported geometry. Do not edit.\n` +
      `// Points are in the inspector's frame: glTF axes, centred on the model's bounding box.\n` +
      `type V3 = [number, number, number]\n` +
      `export interface Measured { anchors: Record<string, V3>; size: V3; hull: V3[]; centre: V3; parts: number; skinned: boolean; anchorBones: Record<string, string> }\n` +
      `export const ANCHORS: Record<string, Measured> = ` +
      JSON.stringify(Object.fromEntries(Object.entries(measured).map(([k, v]) => [k, { anchors: v.anchors, size: v.size, hull: v.hull, centre: v.centre, parts: v.parts, skinned: v.skinned, anchorBones: v.anchorBones }]))) +
      `\n`
  )
  console.log('anchors -> src/lib/anchors.generated.ts')
}
